const mongoose = require("mongoose");
let reportSchema = new mongoose.Schema({
	"ACN" : String,
	"Local Time Of Day" : String,
	"Flight Conditions" : String,
	"Light" : String,
	"Make Model Name" : String,
	"Crew Size" : String,
	"Mission" : String,
	"Flight Phase" : Array,
	"Location Of Person" : Array,
	"Location In Aircraft" : String,
	"Function" : Array,
	"Qualification" : Array,
	"Anomaly" : Array,
	"Detector" : Array,
	"When Detected" : Array,
	"Result" : Array,
	"Contributing Factors / Situations" : Array,
	"Primary Problem" : Array,
	"Narrative" : String,
	"Human Factors" : Array,
	"Make" : String,
	"Model" : String,
	"Class" : String,
	"Prop" : String,
	"HF_Enc" : Array,
	"Pri_Enc" : Array,
	"Result_Enc" : Array,
	"Sit_Enc" : Array,
	"nltk_tokens" : Array,
	"spacy_tokens" : Array,
	"BERT" : Array,
	"eng_features" : Array,
	"features_only" : Array,
	"ten_plus" : Boolean,
	"roBERTa" : Array,
	"doc2vec" : Array,
	"class" : String,
	"Result_Code" : Array,
	"Sit_Code" : Array,
	"Pri_Code" : Array,
	"Hf_Code" : Array,
	"tfid_word__vector_spacy" : Array,
	"tfid_word_vector_nltk" : Array,
	"eng_features_code" : Array,
	"features_only_code" : Array,
	"sample" : Boolean,
	"lda_topic": String,
	"lsa_topic": String,
	"nmf_topic": String,
	"lda_keywords": Array,
	"lsa_keywords": Array,
	"nmf_keywords": Array,
	"lda_xy": Array,
	"lsa_xy": Array,
	"nmf_xy": Array,
	"top_15":Array,
	"ner": Array,
	"sentiment": String,
	"objective": String
},
{ 
	collection : 'nas_dropped_version' 
}
);
module.exports = mongoose.model("Report", reportSchema, 'nas_dropped_version');